apiVersion: v1
kind: Service
metadata:
  name: finance-app-svc   # 웹 서버 서비스 이름
  namespace: finance-app  # 동일한 가상 방에 안착
spec:
  type: ClusterIP
  selector:
    app: finance-app      # 내 Deployment의 라벨 명찰을 조준
  ports:
  - port: 80
    targetPort: 8080      # 내 스프링 부트 컨테이너의 8080 구멍으로 패킷 토스